import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Boxes, GraduationCap, Layers, ListChecks, Sparkles } from 'lucide-react'
import clsx from 'clsx'
import { PageMotion } from '@/components/layout/PageMotion'
import { GlassCard } from '@/components/ui/GlassCard'
import { Spinner } from '@/components/ui/Spinner'
import { FlashcardDeck } from '@/features/study/FlashcardDeck'
import { Quiz } from '@/features/study/Quiz'
import { useClusters, useStudySet } from '@/hooks/useStudy'

type Mode = 'flashcards' | 'quiz'

export default function Study() {
  const { data: clusters, isLoading: loadingClusters } = useClusters()
  const [searchParams] = useSearchParams()
  const requestedId = searchParams.get('cluster')
  const [activeId, setActiveId] = useState<number | null>(null)
  const [mode, setMode] = useState<Mode>('flashcards')

  useEffect(() => {
    if (!clusters?.length) return
    if (activeId != null) return
    const wanted = requestedId ? Number(requestedId) : null
    const exists = clusters.find((c) => c.id === wanted)
    setActiveId(exists ? exists.id : clusters[0].id)
  }, [clusters, activeId, requestedId])

  const { data: study, isFetching } = useStudySet(activeId, 8)

  if (!loadingClusters && !clusters?.length) {
    return (
      <PageMotion>
        <GlassCard hover={false} className="flex flex-col items-center gap-3 py-20 text-center">
          <GraduationCap size={40} className="text-slate-600" />
          <p className="text-slate-300">No concept clusters yet.</p>
          <p className="text-sm text-slate-500">
            Add a document in the{' '}
            <Link to="/library" className="text-neon-cyan hover:underline">
              Library
            </Link>{' '}
            or run <code className="font-mono">python seed.py</code> to build study sets.
          </p>
        </GlassCard>
      </PageMotion>
    )
  }

  return (
    <PageMotion>
      <div className="grid gap-4 lg:grid-cols-4">
        {/* cluster picker */}
        <GlassCard hover={false} className="lg:col-span-1">
          <h2 className="mb-1 flex items-center gap-2 font-semibold text-white">
            <Boxes size={16} className="text-neon-cyan" /> Topics
          </h2>
          <p className="mb-3 text-xs text-slate-400">Each is a cluster from your Mind Palace.</p>
          {loadingClusters ? (
            <div className="grid place-items-center py-10">
              <Spinner className="h-6 w-6" />
            </div>
          ) : (
            <div className="space-y-2">
              {clusters?.map((c) => (
                <button
                  key={c.id}
                  onClick={() => setActiveId(c.id)}
                  className={clsx(
                    'w-full rounded-xl border px-3 py-2.5 text-left transition-all',
                    activeId === c.id
                      ? 'border-neon-purple/40 bg-white/10 shadow-glow'
                      : 'border-white/10 bg-white/5 hover:bg-white/10',
                  )}
                >
                  <p className="truncate text-sm font-medium text-slate-100">{c.title}</p>
                  <p className="text-[11px] text-slate-500">{c.size} concepts</p>
                </button>
              ))}
            </div>
          )}
        </GlassCard>

        {/* study panel */}
        <GlassCard hover={false} className="lg:col-span-3">
          <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="font-semibold text-white">{study?.cluster.title ?? 'Study set'}</h2>
              <p className="text-xs text-slate-400">
                {study?.mode === 'ollama'
                  ? 'Generated by Ollama'
                  : study?.mode === 'claude'
                    ? 'Generated by Claude'
                    : 'Generated from your documents'}
              </p>
            </div>
            <div className="inline-flex rounded-xl border border-white/10 bg-white/5 p-1 text-sm">
              <button
                onClick={() => setMode('flashcards')}
                className={clsx(
                  'flex items-center gap-1.5 rounded-lg px-3 py-1.5 transition-colors',
                  mode === 'flashcards' ? 'bg-white/10 text-white' : 'text-slate-400',
                )}
              >
                <Layers size={14} /> Flashcards
              </button>
              <button
                onClick={() => setMode('quiz')}
                className={clsx(
                  'flex items-center gap-1.5 rounded-lg px-3 py-1.5 transition-colors',
                  mode === 'quiz' ? 'bg-white/10 text-white' : 'text-slate-400',
                )}
              >
                <ListChecks size={14} /> Quiz
              </button>
            </div>
          </div>

          {isFetching || !study ? (
            <div className="grid place-items-center py-24">
              <div className="flex flex-col items-center gap-3 text-slate-400">
                <Spinner className="h-7 w-7" />
                <span className="text-sm">Building your study set…</span>
              </div>
            </div>
          ) : (
            <motion.div
              key={`${activeId}-${mode}`}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="mx-auto max-w-2xl"
            >
              {mode === 'flashcards' ? (
                <FlashcardDeck cards={study.flashcards} />
              ) : (
                <Quiz questions={study.quiz} />
              )}
            </motion.div>
          )}
        </GlassCard>
      </div>

      <GlassCard className="mt-4 flex items-center justify-between" delay={0.1}>
        <p className="text-sm text-slate-400">
          <Sparkles size={14} className="mr-1 inline text-neon-cyan" />
          Want richer, fully-written cards? Run a local Ollama model — it takes over automatically.
        </p>
        <Link to="/palace" className="btn-ghost text-xs">
          <Boxes size={14} /> View in 3D
        </Link>
      </GlassCard>
    </PageMotion>
  )
}
